# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/machyn/CLionProjects/PSTL-Tri-optimise

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/machyn/CLionProjects/PSTL-Tri-optimise

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/machyn/CLionProjects/PSTL-Tri-optimise/CMakeFiles /home/machyn/CLionProjects/PSTL-Tri-optimise/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/machyn/CLionProjects/PSTL-Tri-optimise/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sort

# Build rule for target.
sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sort
.PHONY : sort

# fast build rule for target.
sort/fast:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/build
.PHONY : sort/fast

src/Generator.o: src/Generator.cpp.o

.PHONY : src/Generator.o

# target to build an object file
src/Generator.cpp.o:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/Generator.cpp.o
.PHONY : src/Generator.cpp.o

src/Generator.i: src/Generator.cpp.i

.PHONY : src/Generator.i

# target to preprocess a source file
src/Generator.cpp.i:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/Generator.cpp.i
.PHONY : src/Generator.cpp.i

src/Generator.s: src/Generator.cpp.s

.PHONY : src/Generator.s

# target to generate assembly for a file
src/Generator.cpp.s:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/Generator.cpp.s
.PHONY : src/Generator.cpp.s

src/ToolBox.o: src/ToolBox.cpp.o

.PHONY : src/ToolBox.o

# target to build an object file
src/ToolBox.cpp.o:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/ToolBox.cpp.o
.PHONY : src/ToolBox.cpp.o

src/ToolBox.i: src/ToolBox.cpp.i

.PHONY : src/ToolBox.i

# target to preprocess a source file
src/ToolBox.cpp.i:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/ToolBox.cpp.i
.PHONY : src/ToolBox.cpp.i

src/ToolBox.s: src/ToolBox.cpp.s

.PHONY : src/ToolBox.s

# target to generate assembly for a file
src/ToolBox.cpp.s:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/ToolBox.cpp.s
.PHONY : src/ToolBox.cpp.s

src/VectorGenerator.o: src/VectorGenerator.cpp.o

.PHONY : src/VectorGenerator.o

# target to build an object file
src/VectorGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/VectorGenerator.cpp.o
.PHONY : src/VectorGenerator.cpp.o

src/VectorGenerator.i: src/VectorGenerator.cpp.i

.PHONY : src/VectorGenerator.i

# target to preprocess a source file
src/VectorGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/VectorGenerator.cpp.i
.PHONY : src/VectorGenerator.cpp.i

src/VectorGenerator.s: src/VectorGenerator.cpp.s

.PHONY : src/VectorGenerator.s

# target to generate assembly for a file
src/VectorGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/VectorGenerator.cpp.s
.PHONY : src/VectorGenerator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sort"
	@echo "... edit_cache"
	@echo "... src/Generator.o"
	@echo "... src/Generator.i"
	@echo "... src/Generator.s"
	@echo "... src/ToolBox.o"
	@echo "... src/ToolBox.i"
	@echo "... src/ToolBox.s"
	@echo "... src/VectorGenerator.o"
	@echo "... src/VectorGenerator.i"
	@echo "... src/VectorGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

